### ISSUE TITLE
dotnet-musicstore

### ISSUE THREAD

**Issue by amarie401** [amarie401/tye-test-projects#13]
### Properties removed and/or unsupported in Tye currently:
* healthcheck
  * test
  * interval
  * retries

* depends_on:
  * db:
     * condition: service_healthy

* web:
    * build:
      * context: .
      * dockerfile: Dockerfile.windows

* networks:
  * default:
    * external:
      * name: nat

### Blockers preventing completion:
* Error when trying to build the windows image when calling `tye run` .
Error message: `"image operating system "windows" cannot be used on this platform"`

**Comment by amarie401** [comment]
@davidfowl for visibility

**Comment by amarie401** [comment]
@rynowak for visibility as well since this is the one we worked on together.

**Comment by amarie401** [comment]
@davidfowl 

Hmm...this may have something to do with my Docker settings and needing to change it to run window containers? I'll try that and see if it works. If so, then we will need to make note of that since users may need to change their Docker settings when trying to run Tye on this sample.

**Comment by davidfowl** [comment]
Yes it seems like you have Windows containers instead of Linux containers

**Comment by rynowak** [comment]
Wait does this sample use windows containers? I'm not sure we want that if so.

**Comment by amarie401** [comment]
It appears the that I needed to switch my docker settings to use Windows containers instead of Linux containers. I have made note of that in the readme if folks want to call `tye run` on it.

**Comment by davidfowl** [comment]
@amarie401 I think @rynowak was saying we don't really care about windows containers for this sample 😄 . Switch your settings back and nuke this sample.

**Comment by amarie401** [comment]
Ahhh gotcha okay hehe
